config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: "registrations",
    invitations: "invitations",
    passwords: "passwords",
    confirmations: "confirmations"
  }

  devise_scope :user do
    get "/enter", to: "registrations#new", as: :sign_up
    get "/confirm-email", to: "confirmations#new"
    delete "/sign_out", to: "devise/sessions#destroy"
  end

  get "/r/mobile", to: "deep_links#mobile"
  get "/.well-known/apple-app-site-association", to: "deep_links#aasa"

  scope "(/::locale)", locale: /#{I18n.fallbacks.keys.join("|")}/ do
    draw :admin

    constraints(->(_req) { Listing.feature_enabled? }) do
      draw :listing
    end

    namespace :stories, defaults: { format: "json" } do
      resource :feed, only: [:show] do
        resource :pinned_article, only: %w[show update destroy]

        get ":timeframe", to: "feeds#show", as: :timeframe
      end
    end

    namespace :api, defaults: { format: "json" } do
      scope module: :v1, constraints: ApiConstraints.new(version: 1, default: false) do
        put "/users/:id/suspend", to: "users#suspend", as: :user_suspend
        put "/articles/:id/unpublish", to: "articles#unpublish", as: :article_unpublish
        put "/users/:id/unpublish", to: "users#unpublish", as: :user_unpublish

        post "/reactions", to: "reactions#create"
        post "/reactions/toggle", to: "reactions#toggle"

        resources :billboards, only: %i[index show create update] do
          put "unpublish", on: :member
        end
        resources :display_ads, only: %i[index show create update], controller: :billboards do
          put "unpublish", on: :member
        end

        resources :segments, controller: "audience_segments", only: %i[index show create destroy] do
          get "users", on: :member
          put "add_users", on: :member
          put "remove_users", on: :member
        end

        resources :pages, only: %i[index show create update destroy]

        resources :organizations, only: %i[index create update destroy]

        draw :api
      end

      scope module: :v0, constraints: ApiConstraints.new(version: 0, default: true) do
        draw :api
      end
    end

    namespace :notifications do
      resources :counts, only: [:index]
      resources :reads, only: [:create]
    end

    namespace :incoming_webhooks do
      get "/mailchimp/:secret/unsubscribe", to: "mailchimp_unsubscribes#index", as: :mailchimp_unsubscribe_check
      post "/mailchimp/:secret/unsubscribe", to: "mailchimp_unsubscribes#create", as: :mailchimp_unsubscribe
    end

    resources :messages, only: [:create]
    resources :articles, only: %i[update create destroy] do
      patch "/admin_unpublish", to: "articles#admin_unpublish"
      patch "/admin_featured_toggle", to: "articles#admin_featured_toggle"
    end
    resources :article_mutes, only: %i[update]
    resources :comments, only: %i[create update destroy] do
      patch "/hide", to: "comments#hide"
      patch "/unhide", to: "comments#unhide"
      patch "/admin_delete", to: "comments#admin_delete"
      collection do
        post "/moderator_create", to: "comments#moderator_create"
      end
    end
    resources :comment_mutes, only: %i[update]
    resources :users, only: %i[index], defaults: { format: :json } do # internal API
      collection do
        resources :devices, only: %i[create destroy]
      end
    end
    namespace :users do
      resource :settings, only: %i[update]
      resource :notification_settings, only: %i[update]
    end
    resources :users, only: %i[update]
    resources :reactions, only: %i[index create]
    resources :response_templates, only: %i[index create edit update destroy]
    resources :feedback_messages, only: %i[index create]
    resources :organizations, only: %i[update create destroy]
    resources :follows, only: %i[show create] do
      collection do
        get "/bulk_show", to: "follows#bulk_show"
        patch "/bulk_update", to: "follows#bulk_update"
      end
    end
    resources :image_uploads, only: [:create]
    resources :notifications, only: [:index]
    resources :tags, only: [:index] do
      collection do
        get "/suggest", to: "tags#suggest", defaults: { format: :json }
        get "/bulk", to: "tags#bulk", defaults: { format: :json }
      end
    end
    resources :stripe_active_cards, only: %i[create update destroy]
    resources :github_repos, only: %i[index] do
      collection do
        post "/update_or_create", to: "github_repos#update_or_create"
      end
    end
    resources :videos, only: %i[index create new]
    resources :video_states, only: [:create]
    resources :twilio_tokens, only: [:show]
    resources :tag_adjustments, only: %i[create destroy]
    resources :rating_votes, only: [:create]
    resources :page_views, only: %i[create update]
    resources :credits, only: %i[index new create] do
      get "purchase", on: :collection, to: "credits#new"
    end
    resources :reading_list_items, only: [:update]
    resources :poll_votes, only: %i[show create]
    resources :poll_skips, only: [:create]
    resources :profile_pins, only: %i[create update]
    resources :display_ad_events, only: [:create], controller: :billboard_events
    resources :billboard_events, only: [:create]
    resources :badges, only: [:index]
    resources :user_blocks, param: :blocked_id, only: %i[show create destroy]
    resources :podcasts, only: %i[new create]
    resources :article_approvals, only: %i[create]
    resources :sidebars, only: %i[show]
    resources :profile_preview_cards, only: %i[show]
    resources :user_subscriptions, only: %i[create] do
      collection do
        get "/subscribed", action: "subscribed"
      end
    end

    namespace :followings, defaults: { format: :json } do
      get :users
      get :tags
      get :organizations
      get :podcasts
    end

    resource :onboarding, only: %i[show update] do
      member do
        patch :checkbox, defaults: { format: :json }
        patch :notifications, defaults: { format: :json }
        get :tags, defaults: { format: :json }
        get :users_and_organizations, defaults: { format: :json }
      end
    end

    resources :profiles, only: %i[update]
    resources :profile_field_groups, only: %i[index], defaults: { format: :json }

    resources :liquid_tags, only: %i[index], defaults: { format: :json }

    resources :discussion_locks, only: %i[create destroy]

    get "/verify_email_ownership", to: "email_authorizations#verify", as: :verify_email_authorizations
    get "/search/tags", to: "search#tags"
    get "/search/usernames", to: "search#usernames"
    get "/search/feed_content", to: "search#feed_content"
    get "/search/reactions", to: "search#reactions"
    get "/notifications/:filter", to: "notifications#index", as: :notifications_filter
    get "/notifications/:filter/:org_id", to: "notifications#index", as: :notifications_filter_org
    get "/notification_subscriptions/:notifiable_type/:notifiable_id", to: "notification_subscriptions#show"
    post "/notification_subscriptions/:notifiable_type/:notifiable_id", to: "notification_subscriptions#upsert"
    get "email_subscriptions/unsubscribe"

    get "/internal", to: redirect("/admin")
    get "/internal/:path", to: redirect("/admin/%{path}")

    get "/social_previews/article/:id", to: "social_previews#article", as: :article_social_preview

    get "/async_info/base_data", to: "async_info#base_data", defaults: { format: :json }
    get "/async_info/navigation_links", to: "async_info#navigation_links"

    scope "/:username/:slug" do
      get "/billboards/:placement_area", to: "billboards#show", as: :article_billboard
      get "/display_ads/:placement_area", to: "billboards#show"
    end
    get "/billboards/:placement_area", to: "billboards#show", as: :billboard
    get "/display_ads/:placement_area", to: "billboards#show"

    post "users/join_org", to: "users#join_org"
    post "users/leave_org/:organization_id", to: "users#leave_org", as: :users_leave_org
    post "users/add_org_admin", to: "users#add_org_admin"
    post "users/remove_org_admin", to: "users#remove_org_admin"
    post "users/remove_from_org", to: "users#remove_from_org"
    delete "users/remove_identity", to: "users#remove_identity"
    post "users/request_destroy", to: "users#request_destroy", as: :user_request_destroy
    get "users/confirm_destroy/:token", to: "users#confirm_destroy", as: :user_confirm_destroy
    delete "users/full_delete", to: "users#full_delete", as: :user_full_delete
    post "organizations/generate_new_secret", to: "organizations#generate_new_secret"
    post "users/api_secrets", to: "api_secrets#create", as: :users_api_secrets
    delete "users/api_secrets/:id", to: "api_secrets#destroy", as: :users_api_secret
    post "users/update_password", to: "users#update_password", as: :user_update_password

    get "/robots.:format", to: "pages#robots"
    get "/api", to: redirect("https://developers.forem.com/api")
    get "/privacy", to: "pages#privacy"
    get "/terms", to: "pages#terms"
    get "/contact", to: "pages#contact"
    get "/code-of-conduct", to: "pages#code_of_conduct"
    get "/report-abuse", to: "pages#report_abuse"
    get "/welcome", to: "pages#welcome"
    get "/challenge", to: "pages#challenge"
    get "/checkin", to: "pages#checkin"
    get "/💸", to: redirect("t/hiring")
    get "/survey", to: redirect("https://dev.to/ben/final-thoughts-on-the-state-of-the-web-survey-44nn")
    get "/search", to: "stories/articles_search#index"
    get "/:slug/members", to: "organizations#members", as: :organization_members
    post "articles/preview", to: "articles#preview"
    post "comments/preview", to: "comments#preview"
    post "comments/subscribe", to: "notification_subscriptions#create"
    post "subscription/unsubscribe", to: "notification_subscriptions#destroy"

    get "/about", to: "pages#about"

app/controllers/admin/listings_controller.rb
module Admin
  class ListingsController < Admin::ApplicationController
    ALLOWED_PARAMS = %i[
      published body_markdown title category listing_category_id tag_list action organization_id
    ].freeze
    layout "admin"

    def index
      @listings =
        Listing.includes(%i[user listing_category])
          .page(params[:page]).order(bumped_at: :desc).per(50)

      @listings = @listings.published unless include_unpublished?
      @listings = @listings.in_category(params[:filter]) if params[:filter].present?
    end

    def edit
      @listing = Listing.find(params[:id])
    end

    def update
      @listing = Listing.find(params[:id])
      handle_publish_status if listing_params[:published]

      if listing_params[:action] == "bump"
        bump_success = Listings::Bump.call(@listing, user: current_user)
        return process_no_credit_left unless bump_success
      end

      @listing.update(listing_params.compact)
      @listing.clear_cache
      flash[:success] = I18n.t("admin.listings_controller.updated")
      redirect_to edit_admin_listing_path(@listing)
    end

    def destroy
      @listing = Listing.find(params[:id])
      @listing.destroy
      flash[:warning] = I18n.t("admin.listings_controller.destroyed", title: @listing.title)
      redirect_to admin_listings_path
    end

    private

    private_constant :ALLOWED_PARAMS

    def listing_params
      params.require(:listing).permit(ALLOWED_PARAMS)
    end

    def handle_publish_status
      @listing.unpublish if listing_params[:published] == "0"
      @listing.publish if listing_params[:published] == "1"
    end

    def include_unpublished?
      params[:include_unpublished] == "1"
    end

    def process_no_credit_left
      redirect_to admin_listings_path, notice: I18n.t("admin.listings_controller.no_credit")
    end
  end
end

app/controllers/api/v0/listings_controller.rb
module Api
  module V0
    class ListingsController < ApiController
      include Api::ListingsController

      # actions `create` and `update` are defined in the module `ListingsToolkit`,
      # we thus silence Rubocop lexical scope filter cop: https://rails.rubystyle.guide/#lexically-scoped-action-filter
      before_action :authenticate_with_api_key_or_current_user!, only: %i[create update]
      before_action :authenticate_with_api_key_or_current_user, only: %i[show]
      before_action :set_cache_control_headers, only: %i[index show]
      before_action :set_and_authorize_listing, only: %i[update]
      skip_before_action :verify_authenticity_token, only: %i[create update]
    end
  end
end

app/controllers/api/v1/listings_controller.rb
module Api
  module V1
    class ListingsController < ApiController
      include Api::ListingsController

      # actions `create` and `update` are defined in the module `ListingsToolkit`,
      # we thus silence Rubocop lexical scope filter cop: https://rails.rubystyle.guide/#lexically-scoped-action-filter
      before_action :authenticate_with_api_key_or_current_user!, only: %i[create update]
      before_action :authenticate_with_api_key_or_current_user, only: %i[show]
      before_action :set_cache_control_headers, only: %i[index show]
      before_action :set_and_authorize_listing, only: %i[update]
    end
  end
end

app/controllers/concerns/api/listings_controller.rb
module Api
  module ListingsController
    extend ActiveSupport::Concern

    include Pundit::Authorization
    include ListingsToolkit

    # NOTE: since this is used for selecting from the DB, we need to use the
    # actual column name for the listing category, prefixed with classified_.
    ATTRIBUTES_FOR_SERIALIZATION = %i[
      id user_id organization_id title slug body_markdown cached_tag_list
      classified_listing_category_id processed_html published created_at
    ].freeze
    private_constant :ATTRIBUTES_FOR_SERIALIZATION

    def index
      @listings = Listing.published
        .select(ATTRIBUTES_FOR_SERIALIZATION)
        .includes([{ user: :profile }, :organization, :taggings, :listing_category])

      if params[:category].present?
        @listings = @listings.in_category(params[:category])
      end
      @listings = @listings.order(bumped_at: :desc)

      per_page = (params[:per_page] || 30).to_i
      per_page_max = (ApplicationConfig["API_PER_PAGE_MAX"] || 100).to_i
      num = [per_page, per_page_max].min
      page = params[:page] || 1
      @listings = @listings.page(page).per(num)

      set_surrogate_key_header Listing.table_key, @listings.map(&:record_key)
    end

    def show
      relation = Listing.published

      # if the user is authenticated we allow them to access
      # their own unpublished listings as well
      relation = relation.union(@user.listings) if @user

      @listing = relation.select(ATTRIBUTES_FOR_SERIALIZATION).find(params[:id])

      set_surrogate_key_header @listing.record_key
    end

    private

    attr_accessor :user

    alias current_user user

    def process_no_credit_left
      msg = I18n.t("api.v0.listings_controller.no_credit")
      render json: { error: msg, status: 402 }, status: :payment_required
    end

    def process_successful_draft
      render "show", status: :created
    end

    def process_unsuccessful_draft
      render json: { errors: @listing.errors }, status: :unprocessable_entity
    end

    def process_successful_creation
      render "show", status: :created
    end

    def process_unsuccessful_creation
      render json: { errors: @listing.errors }, status: :unprocessable_entity
    end

    alias process_unsuccessful_update process_unsuccessful_creation

    def process_after_update
      render "show", status: :ok
    end

    def process_after_unpublish
      render "show", status: :ok
    end

    # Since our documentation examples now use "listing", prefer that,
    # but permit the legacy parameter "classified_listing",
    # since this was a published API before the refactoring renamed
    # ClassifiedListing to Listing in https://github.com/forem/forem/pull/7910
    def listing_params
      params["listing"] ||= params["classified_listing"]
      if (category_id = find_category_id(params.dig("listing", "category")))
        params["listing"]["listing_category_id"] = category_id
      end
      super
    end

    def find_category_id(slug)
      return if slug.blank?

      ListingCategory.select(:id).find_by(slug: slug)&.id
    end
  end
end

app/helpers/listing_helper.rb
module ListingHelper
  def select_options_for_categories
    ListingCategory.select(:id, :slug, :name, :cost).map do |cl|
      [I18n.t("helpers.listing_helper.option", cl_name: cl.name, count: cl.cost), cl.slug, cl.id]
    end
  end

  def categories_for_display
    ListingCategory.pluck(:slug, :name).map do |slug, name|
      { slug: slug, name: name }
    end
  end

  def categories_available
    ListingCategory.all.each_with_object({}) do |cat, h|
      h[cat.slug] = cat.attributes.slice("cost", "name", "rules")
    end.deep_symbolize_keys
  end
end

app/views/admin/listings/edit.html.erb
<header class="mb-6 flex items-center">
  <h1 class="crayons-title mb-4">Edit</h1>

  <div class="ml-auto flex">
    <%= link_to "Remove", url_for(action: :destroy, id: @listing.id), method: :delete, data: { confirm: "Are you sure?" }, class: "crayons-btn crayons-btn--danger mr-2" %>

    <%= form_with model: [:admin, @listing], method: :patch do |f| %>
      <input type="hidden" name="listing[action]" value="bump" />
      <%= f.submit "Bump Listing ⏫", class: "crayons-btn crayons-btn--secondary" %>
    <% end %>

    <%= link_to "View", listing_slug_path(category: @listing.category, slug: @listing.slug), target: "_blank", rel: "noopener", class: "crayons-btn crayons-btn--primary ml-2" %>

  </div>
</header>

<div class="crayons-card p-6">
  <%= form_with model: [:admin, @listing], method: :patch, local: true do |form| %>
    <div class="flex flex-col gap-4">
      <div class="crayons-field">
        <%= form.label :title, class: "crayons-field__label" %>
        <%= form.text_field :title, size: 100, maxlength: 128, class: "crayons-textfield" %>
      </div>
      <div class="crayons-field">
        <%= form.label :body_markdown, class: "crayons-field__label" %>
        <%= form.text_area :body_markdown, cols: 40, rows: 15, maxlength: 400, class: "crayons-textfield" %>
      </div>
      <div class="crayons-field">
        <%= form.label :tag_list, class: "crayons-field__label" %>
        <i class="fs-s">Comma separated, one space, 8 tags max</i>
        <%= form.text_field :tag_list, value: @listing.cached_tag_list, size: 100, class: "crayons-textfield" %>
      </div>
      <div class="crayons-field">
        <%= form.label :organization_id, "Organization ID (Optional)", class: "crayons-field__label" %>
        <%= form.text_field :organization_id, value: @listing.organization_id, class: "crayons-textfield" %>
      </div>
      <div class="crayons-field">
        <%= form.label :listing_category_id, class: "crayons-field__label" %>
        <%= form.select :listing_category_id, select_options_for_categories, class: "crayons-select" %>
      </div>
      <div class="crayons-field crayons-field--checkbox">
        <%= form.check_box :published, checked: @listing.published?, class: "crayons-checkbox" %>
        <%= form.label :published, class: "crayons-field__label" %>
      </div>
      <%= form.submit "Update Listing", class: "crayons-btn crayons-btn--primary mr-auto" %>
    </div>
  <% end %>
</div>

app/views/admin/listings/index.html.erb
<header class="flex items-center mb-6">
  <h1 class="crayons-title">Listings</h1>

  <a
    href="<%= admin_listing_categories_path %>"
    aria-label="Listing Categories"
    class="ml-auto crayons-btn">
    Listing Categories
  </a>
</header>

<%= form_tag(admin_listings_path, method: "get", role: "search", class: "crayons-card crayons-card--secondary p-4 flex items-center") do %>
  <div class="mr-4">
    <%= label_tag(:search, "Keyword", class: "mb-0") %>
    <%= text_field_tag(:search, params[:search]) %>
    <% if params[:state].present? %>
      <%= hidden_field_tag(:state, params[:state]) %>
    <% end %>
  </div>

  <div class="mr-4">
    <%= label_tag(:filter, "Category", class: "mb-0") %>
    <%= select_tag(:filter, options_for_select(categories_available.keys, params[:filter]), include_blank: true) %>
  </div>

  <div class="mr-4">
    <%= label_tag(:include_unpublished, "Include unpublished listings", class: "mb-0") %>
    <%= hidden_field_tag(:include_unpublished, 0) %>
    <%= check_box_tag(:include_unpublished, 1, params[:include_unpublished] == "1") %>
  </div>

  <%= submit_tag("Filter") %>
<% end %>

<%= paginate @listings %>

<table class="crayons-table">
  <thead>
    <tr>
      <th scope="col">Title Link</th>
      <th scope="col">User</th>
      <th scope="col">Org</th>
      <th scope="col">Category</th>
      <th scope="col">Cached Tags</th>
      <th scope="col">Published?</th>
      <th scope="col">Last Bumped</th>
    </tr>
  </thead>
  <tbody class="crayons-card">
    <% @listings.each do |listing| %>
      <tr>
        <td><%= link_to listing.title, edit_admin_listing_path(listing.id), rel: "noopener" %></td>
        <td><%= link_to listing.user.username, admin_user_path(listing.user.id) %></td>
        <td><%= link_to listing.organization.name, admin_organization_path(listing.organization_id) if listing.organization_id.present? %></td>
        <td><%= listing.category %></td>
        <td><%= listing.cached_tag_list %></td>
        <td><%= listing.published ? "Yes" : "No" %></td>
        <td><%= listing.bumped_at ? "#{time_ago_in_words(listing.bumped_at)} ago" : "Draft" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @listings %>